name: arungi_rasa
description: App Arungi Rasa

# The following line prevents the package from being accidentally published to
# pub.dev using `pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
version: 0.0.8+8

environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter

  #core
  get: ^4.3.8
  json_annotation: ^4.1.0
  uuid: ^3.0.4

  #widget
  im_stepper: ^0.1.3
  gradient_loading_button: ^0.1.0-nullsafety.0
  octo_image: ^1.0.0+1
  badges: ^2.0.1
  select_dialog: ^2.0.0
  card_swiper: ^1.0.4
  flutter_rating_bar: ^4.0.0

  #widget with native
  cached_network_image: ^3.1.0
  mapbox_gl:
    git:
      url: https://github.com/tobrun/flutter-mapbox-gl.git

  #utility
  flutter_easyloading: ^3.0.0
  ant_icons: ^2.0.0-nullsafety.0
  get_connect_repo_mixin:
    git:
      url: https://github.com/LeonColt/get_connect_repo_mixin.git
      ref: 0.0.3

  #utility with native
  google_sign_in: ^5.0.7
  shared_preferences: ^2.0.6
  pref: ^2.4.0
  flutter_keyboard_visibility: ^5.0.3
  image_picker: ^0.8.3+2
  image_cropper: ^1.4.1
  location: ^4.3.0
  geocoding: ^2.0.0
  document_scanner_flutter: ^0.2.5
  path_provider: ^2.0.2
  flutter_image_compress: ^1.1.0

  #firebase
  firebase_core: ^1.5.0
  firebase_auth: ^3.0.2
  firebase_messaging: ^10.0.5
  firebase_crashlytics: ^2.2.0
  firebase_storage: ^10.0.2

dependency_overrides:
  args: ^2.2.0
  meta: ^1.7.0
  analyzer: ^2.0.0
  image: ^3.0.2
  mapbox_gl_platform_interface:
    git:
      url: https://github.com/tobrun/flutter-mapbox-gl.git
      path: mapbox_gl_platform_interface
  mapbox_gl_web:
    git:
      url: https://github.com/tobrun/flutter-mapbox-gl.git
      path: mapbox_gl_web

dev_dependencies:
  flutter_test:
    sdk: flutter
  build_runner: ^2.1.1
  json_serializable: ^5.0.0
  flutter_gen_runner: ^3.1.2
  flutter_launcher_icons: ^0.9.2
  flutter_native_splash: ^1.2.1

flutter_gen:
  output: lib/generated/

flutter_icons:
  android: "ic_launcher"
  ios: false,
  image_path: "images/logo_icon.png"

flutter_native_splash:
  image: "images/logo_icon.png"
  color: "FFFFFF"
  ios: false
  fill: false

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  # assets:
  #   - images/a_dot_burr.jpeg
  #   - images/a_dot_ham.jpeg
  assets:
    - images/

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware.

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
  fonts:
    - family: Gotham HTF
      fonts:
        - asset: fonts/GOTHAMHTF.OTF
        - asset: fonts/GOTHAMHTF-LIGHT.OTF
          style: normal
    - family: Moneta Sans
      fonts:
        - asset: fonts/MONETASANS-BOLD.OTF
          weight: 700
flutter_intl:
  enabled: true
  main_locale: id
